package br.com.digital.store.strings

object StringsUtils {
    const val CLEAN = "Limpar"
    const val MAIN_NAME = "CANDEEIROS BAR"
    const val EMAIL = "Email"
    const val CATEGORY_NAME = "Nome da categoria"
    const val SAVE_CATEGORY = "Salvar categoria"
    const val PASSWORD = "Senha"
    const val CREATE_MY_ACCOUNT = "Criar minha conta"
    const val FORGOT_PASS = "Esqueceu sua senha?"
    const val RESET_PASSWORD = "Recuperar acesso"
    const val ENTER_YOUR_ACCOUNT = "Acessar minha conta"
    const val OR = "ou"
    const val CREATE_ONE_ACCOUNT = "Criar uma conta"
    const val DASHBOARD = "Dashboard"
    const val PDV = "PDV"
    const val CATEGORIES = "Categorias"
    const val ITEMS = "Items"
    const val FOOD = "Pratos"
    const val PRODUCTS = "Produtos"
    const val ORDER = "Pedidos"
    const val RESERVATION = "Reservas"
    const val HISTORY = "Histórico de Vendas"
    const val SETTINGS = "Configurações"
    const val CHANGE_TO_OTHER_ACCOUNT = "Trocar de conta"
    const val EXIT = "Sair do Programa"
    const val NOT_BLANK_OR_EMPTY = "Preencha todos os campos!"
    const val INVALID_EMAIL = "Este email é inválido!"
    const val LOADING = "Carregando…"
}
